server:
  port: 8081
  servlet:
    context-path: /artifactId
security:
  user:
    name: admin
    password: 123456
spring:
  thymeleaf:
    mode: HTML5
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8
    username: root
    password: ********
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    format-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect